POST http://localhost:4000/api/notas
Content-Type: application/json

{
    "content": "Nueva nota",
    "important": true
}
###
POST http://localhost:4000/api/notas
Content-Type: application/json

{
    "content": "Nueva nota 2.0"
}
###
POST http://localhost:4000/api/notas
Content-Type: application/json

{
}